apiVersion: v1
kind: Pod
metadata:
  name: test-app
  labels:
    cloud.org.com/AppCode: AC0001
    cloud.org.com/AzureKeyVault: aks-AC0001-keyvault
    cloud.org.com/AzureKeyVault1a: test-vault-1a
    cloud.org.com/AzureKeyVaultTag_App1: az-keyvault-tag-AC0001
    aadpodidbinding: pod-selector-label
    app: env_injector
spec:
  containers:
  - name: vault-env-1
    image: securityopregistrytest.azurecr.io/secret-injector:v1alpha3
    args:
      - ls
      - -l
      - /usr/local/bin/
    imagePullPolicy: Always
    env:
      - name: AzureKeyVault
        value: aks-AC0001-keyvault
      - name: env_secret_name
        value: secret1@AzureKeyVault
      - name: env_secret_key
        value: key1@AzureKeyVault
      - name: debug
        value: "false"

    imagePullPolicy: Always
