apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.K8s_namespace }}
  labels:
    app: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/version: "{{ .Values.service.Release }}"
    app.kubernetes.io/component: service
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/namespace: {{ .Values.service.K8s_namespace }}
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
  - name: http
    port: {{ .Values.service.containerPort }}
